### ISSUE TITLE
oppo手机oaid问题

### ISSUE THREAD

**Issue by xiaoxiaodiao770** [shuzilm-open-source/Get_Oaid_CNAdid#10]
原来我们oaid获取方法是根据绑定的service获取的同步调用，但是这个针对稍微卡顿一点的手机就是获取不到的  我这边找到一个解决方案是在serviceConnection中onServiceConnected回调方法内走一遍oaid的获取  这样是不是更加严谨一点

**Comment by xiaoxiaodiao770** [comment]
这个地方  使用同步方法从service连接成功中获取  别的也是同理？

**Comment by lgengsy** [comment]
三星手机获取OAID会崩溃，找不到so是什么问题 ？？`java.lang.UnsatisfiedLinkError: No implementation found for void com.bun.miitmdid.supplier.sumsung.SumsungCore$a.onServiceConnected(android.content.ComponentName, android.os.IBinder) (tried Java_com_bun_miitmdid_supplier_sumsung_SumsungCore_00024a_onServiceConnected and Java_com_bun_miitmdid_supplier_sumsung_SumsungCore_00024a_onServiceConnected__Landroid_content_ComponentName_2Landroid_os_IBinder_2)
        at com.bun.miitmdid.supplier.sumsung.SumsungCore$a.onServiceConnected(Native Method)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2067)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2099)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)`

**Comment by shuzilm-open-source** [comment]
> 三星手机获取OAID会崩溃，找不到so是什么问题 ？？`java.lang.UnsatisfiedLinkError: No implementation found for void com.bun.miitmdid.supplier.sumsung.SumsungCore$a.onServiceConnected(android.content.ComponentName, android.os.IBinder) (tried Java_com_bun_miitmdid_supplier_sumsung_SumsungCore_00024a_onServiceConnected and Java_com_bun_miitmdid_supplier_sumsung_SumsungCore_00024a_onServiceConnected__Landroid_content_ComponentName_2Landroid_os_IBinder_2) at com.bun.miitmdid.supplier.sumsung.SumsungCore$a.onServiceConnected(Native Method) at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2067) at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2099) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8016) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)`

获取之前判断下 com.samsung.android.deviceidservice 包支持

**Comment by xiaoxiaodiao770** [comment]
三星找不到原因是anr  要走子线程过

**Comment by liyujiang-gzu** [comment]
> 原来我们oaid获取方法是根据绑定的service获取的同步调用，但是这个针对稍微卡顿一点的手机就是获取不到的 我这边找到一个解决方案是在serviceConnection中onServiceConnected回调方法内走一遍oaid的获取 这样是不是更加严谨一点

在onServiceConnected异步回调里获取才严谨，作者的直接直接同步获取，很大几率还没等远程服务连接上就过了。

**Comment by liyujiang-gzu** [comment]
数字联盟作者的这个获取OAID对异常情况的处理还不严谨，我做了很大的重构，如下：
```aidl
// IDeviceIdService.aidl
package com.samsung.android.deviceidservice;

// Declare any non-default types here with import statements

interface IDeviceIdService {

     String getID();

}
```
```java
        Intent intent = new Intent();
        intent.setClassName("com.samsung.android.deviceidservice", "com.samsung.android.deviceidservice.DeviceIdService");
        boolean isBinded = context.bindService(intent, new ServiceConnection() {
            @Override
            public void onServiceConnected(ComponentName name, IBinder service) {
                try {
                    //IDeviceIdService anInterface = new IDeviceIdService.Stub.asInterface(service);
                    Method asInterface = IDeviceIdService.Stub.class.getDeclaredMethod("asInterface", IBinder.class);
                    IDeviceIdService anInterface = (IDeviceIdService) asInterface.invoke(null, service);
                    String deviceId = anInterface.getID();
                    if (deviceId == null || deviceId.length() == 0) {
                        //异常情况
                    } else {
                         //这才是正常情况
                    }
                } catch (Exception e) {
                     //异常情况
                } finally {
                    context.unbindService(this);
                }
            }

            @Override
            public void onServiceDisconnected(ComponentName name) {
                
            }
        }, Context.BIND_AUTO_CREATE);
        if (!isBinded) {
             //异常情况
        }

```
详见：https://github.com/gzu-liyujiang/Android_CN_OAID/blob/master/library/src/main/java/com/github/gzuliyujiang/oaid/impl/SamsungDeviceIdImpl.java

**Comment by shuzilm-open-source** [comment]
不是拿来即用的，这里开出来的代码有一点细节没处理，大致逻辑有了，可以具体优化哈~

**Comment by zhiujn** [comment]
@shuzilm-open-source 请问你们遇到OAID在某些厂商设备（特别是oppo）上出现的SecurityException异常么？我们集成的OAID版本是1.2.1，从今年8月份升级到这个版本后就没动过，最近从11.25日开始在bugly上出现了大批量的此类异常，几乎都是oppo设备的。
# GetIDWorkThread(204)

java.lang.SecurityException

Package 包名 does not belong to 10606

解析原始
1
android.os.Parcel.createExceptionOrNull(Parcel.java:2472)
2
android.os.Parcel.createException(Parcel.java:2456)
3
android.os.Parcel.readException(Parcel.java:2439)
4
android.os.Parcel.readException(Parcel.java:2381)
5
com.heytap.openid.m_a$m_a$m_a.m_a(Native Method)
6
com.heytap.openid.sdk.m_c.m_c(Native Method)
7
com.heytap.openid.base.m_c$m_b.handleMessage(Native Method)
8
android.os.Handler.dispatchMessage(Handler.java:106)
9
android.os.Looper.loopOnce(Looper.java:233)
10
android.os.Looper.loop(Looper.java:344)
11
android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by shuzilm-open-source** [comment]
> 

初始化填下 Looper.prepare()

**Comment by wangbax** [comment]
> @shuzilm-open-source 请问你们遇到OAID在某些厂商设备（特别是oppo）上出现的SecurityException异常么？我们集成的OAID版本是1.2.1，从今年8月份升级到这个版本后就没动过，最近从11.25日开始在bugly上出现了大批量的此类异常，几乎都是oppo设备的。
> 
> # GetIDWorkThread(204)
> java.lang.SecurityException
> 
> Package 包名 does not belong to 10606
> 
> 解析原始 1 android.os.Parcel.createExceptionOrNull(Parcel.java:2472) 2 android.os.Parcel.createException(Parcel.java:2456) 3 android.os.Parcel.readException(Parcel.java:2439) 4 android.os.Parcel.readException(Parcel.java:2381) 5 com.heytap.openid.m_a$m_a$m_a.m_a(Native Method) 6 com.heytap.openid.sdk.m_c.m_c(Native Method) 7 com.heytap.openid.base.m_c$m_b.handleMessage(Native Method) 8 android.os.Handler.dispatchMessage(Handler.java:106) 9 android.os.Looper.loopOnce(Looper.java:233) 10 android.os.Looper.loop(Looper.java:344) 11 android.os.HandlerThread.run(HandlerThread.java:67)

请问这个有什么解决思路么？

**Comment by mahao521** [comment]
> @shuzilm-open-source 请问你们遇到OAID在某些厂商设备（特别是oppo）上出现的SecurityException异常么？我们集成的OAID版本是1.2.1，从今年8月份升级到这个版本后就没动过，最近从11.25日开始在bugly上出现了大批量的此类异常，几乎都是oppo设备的。
> 
> # GetIDWorkThread(204)
> java.lang.SecurityException
> 
> Package 包名 does not belong to 10606
> 
> 解析原始 1 android.os.Parcel.createExceptionOrNull(Parcel.java:2472) 2 android.os.Parcel.createException(Parcel.java:2456) 3 android.os.Parcel.readException(Parcel.java:2439) 4 android.os.Parcel.readException(Parcel.java:2381) 5 com.heytap.openid.m_a$m_a$m_a.m_a(Native Method) 6 com.heytap.openid.sdk.m_c.m_c(Native Method) 7 com.heytap.openid.base.m_c$m_b.handleMessage(Native Method) 8 android.os.Handler.dispatchMessage(Handler.java:106) 9 android.os.Looper.loopOnce(Looper.java:233) 10 android.os.Looper.loop(Looper.java:344) 11 android.os.HandlerThread.run(HandlerThread.java:67)
遇到了，怎么解决啊？
